[package]
name = "simulator"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[dependencies]
clap = { version = "4.5.14", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.205", features = ["derive"] }
