name: Test Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libasound2-dev

      - name: Set up SSH key for dependency access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_CONDUCTOR_DEV }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

      - name: Configure Git and Cargo to use SSH key
        run: |
          git config core.sshCommand "ssh -i ~/.ssh/deploy_key -o UserKnownHostsFile=/dev/null"
          mkdir -p ~/.cargo
          echo '[net]' > ~/.cargo/config.toml
          echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: make test
